spring:

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      #enabled: false
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml

  jpa:
    generate-ddl: false
    #generate-ddl: true
    hibernate:
      ddl-auto: none
      #ddl-auto: create-drop
    show-sql: true